// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Models;

namespace verbose_disco.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20191107004137_InitialCreate_Orgs")]
    partial class InitialCreate_Orgs
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0");

            modelBuilder.Entity("Models.Org", b =>
                {
                    b.Property<Guid>("sourcedId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("boarding")
                        .HasColumnType("INTEGER");

                    b.Property<string>("classification")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("dateLastModified")
                        .HasColumnType("TEXT");

                    b.Property<string>("gender")
                        .HasColumnType("TEXT");

                    b.Property<string>("identifier")
                        .HasColumnType("TEXT");

                    b.Property<string>("name")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("parentSourcedId")
                        .HasColumnType("TEXT");

                    b.Property<string>("status")
                        .HasColumnType("TEXT");

                    b.Property<string>("type")
                        .HasColumnType("TEXT");

                    b.HasKey("sourcedId");

                    b.ToTable("Orgs");
                });
#pragma warning restore 612, 618
        }
    }
}
